name: C/C++ CI

on: [pull_request, push]

#schedule:
# * is a special character in YAML so you have to quote this string
#  - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cbgeo/mpm:latest
      options:  --user root
    steps:
    - name: Checkout Meta Repo
      uses: actions/checkout@v2
    - name: Configure and build with G++
      run: |
          pwd
          mkdir -p build
          [ "$(ls -A build)" ] && rm -rf build/*
          cd build
          source /etc/profile.d/modules.sh
          export MODULEPATH=$MODULEPATH:/usr/share/modulefiles
          module load mpi/openmpi-x86_64
          export CXX_COMPILER=mpicxx
          cmake -GNinja -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DKAHIP_ROOT=/home/cbgeo/KaHIP/ -DPARTIO_ROOT=/home/cbgeo/partio/ ..
          ninja -j2
          ctest -VV
